- "hosts":
  - "chores.local"
  "name": "chores"
  "tasks":
  - "become": false
    "git":
      "dest": "~/src/chores"
      "repo": "https://github.com/arecker/chores.git"
      "version": "master"
    "name": "git: ~/src/chores"
  - "get_url":
      "dest": "~/bin/launcher"
      "mode": "0755"
      "url": "https://raw.githubusercontent.com/arecker/launcher/main/launcher"
    "name": "get url https://raw.githubusercontent.com/arecker/launcher/main/launcher"
  - "become": false
    "name": "render template: env.j2"
    "template":
      "dest": "~/src/chores/launcher.env"
      "mode": "400"
      "src": "../templates/env.j2"
    "vars":
      "variables":
        "FLASK_ENV": "production"
        "HUB_URL": "http://chores.local"
        "PORT": "5000"
        "PYTHONDONTWRITEBYTECODE": "1"
        "PYTHONUNBUFFERED": "1"
        "WEBHOOK_URL": "{{ secrets.chores_webhook_url }}"
        "WORKERS": "2"
  - "name": "install pip packages: Flask, Flask-SQLAlchemy, SQLAlchemy-Utils, gunicorn, python-dateutil, requests, sqlalchemy"
    "pip":
      "executable": "~/bin/pip"
      "name":
      - "Flask"
      - "Flask-SQLAlchemy"
      - "SQLAlchemy-Utils"
      - "gunicorn"
      - "python-dateutil"
      - "requests"
      - "sqlalchemy"
  - "file":
      "dest": "~/bin/gunicorn"
      "force": true
      "src": "~/.pyenv/versions/3.9.7/bin/gunicorn"
      "state": "link"
    "name": "symlink ~/.pyenv/versions/3.9.7/bin/gunicorn -> ~/bin/gunicorn"
  - "cron":
      "job": "~/bin/launcher --config ~/src/chores/launcher.config"
      "name": "chores site"
      "special_time": "reboot"
    "name": "cron: chores site"
  "vars_files":
  - "secrets/secrets.yml"
