- "hosts":
  - "console.local"
  "name": "console"
  "tasks":
  - "become": true
    "name": "install package: openssh-server"
    "package":
      "name": "openssh-server"
      "state": "present"
      "update_cache": false
  - "become": true
    "name": "render template: sshd.conf.j2"
    "template":
      "dest": "/etc/ssh/sshd_config"
      "group": "root"
      "mode": "644"
      "owner": "root"
      "src": "../templates/sshd.conf.j2"
    "vars":
      "variables": {}
  "vars_files":
  - "secrets/secrets.yml"
