- "hosts":
  - "chores.local"
  - "console.local"
  - "wallpaper.local"
  "name": "python"
  "tasks":
  - "become": true
    "name": "install package: {{ item }}"
    "package":
      "name": "{{ item }}"
      "state": "present"
      "update_cache": false
    "with_items":
    - "build-essential"
    - "curl"
    - "libbz2-dev"
    - "libffi-dev"
    - "liblzma-dev"
    - "libncurses5-dev"
    - "libncursesw5-dev"
    - "libreadline-dev"
    - "libsqlite3-dev"
    - "libssl-dev"
    - "llvm"
    - "make"
    - "tk-dev"
    - "wget"
    - "xz-utils"
    - "zlib1g-dev"
  - "become": true
    "name": "install package: git"
    "package":
      "name": "git"
      "state": "present"
      "update_cache": false
  - "become": false
    "git":
      "dest": "~/.pyenv"
      "repo": "https://github.com/pyenv/pyenv.git"
      "version": "master"
    "name": "git: ~/.pyenv"
  - "command":
      "cmd": "~/.pyenv/bin/pyenv install 3.9.7"
      "creates": "~/.pyenv/versions/3.9.7"
    "name": "command: ~/.pyenv/bin/pyenv install 3.9.7"
  "vars_files":
  - "secrets/secrets.yml"
