- "hosts":
  - "chores.local"
  - "console.local"
  - "jenkins.local"
  - "minecraft.local"
  - "printer.local"
  - "wallpaper.local"
  "name": "ssh"
  "tasks":
  - "become": true
    "name": "install package: openssh-server"
    "package":
      "name": "openssh-server"
      "state": "present"
      "update_cache": false
  - "become": true
    "name": "render template: sshd.conf.j2"
    "template":
      "dest": "/etc/ssh/sshd_config"
      "group": "root"
      "mode": "644"
      "owner": "root"
      "src": "../templates/sshd.conf.j2"
    "vars":
      "variables": {}
  - "become": false
    "name": "render template: ssh.conf.j2"
    "template":
      "dest": "~/.ssh/config"
      "mode": "644"
      "src": "../templates/ssh.conf.j2"
    "vars":
      "variables": {}
  - "authorized_key":
      "key": "{{ lookup(\"file\", \"../keys/\" + item + \".pub\") }}"
      "state": "present"
      "user": "alex"
    "name": "authorized keys: personal, jenkins"
    "with_items":
    - "personal"
    - "jenkins"
  "vars_files":
  - "secrets/secrets.yml"
