language: bash

services:
  - docker

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

before_install: $TRAVIS_BUILD_DIR/build.sh before-install

env:
  - JOB="docker"
  - JOB="terraform"

script: $TRAVIS_BUILD_DIR/build.sh "$JOB"

notifications:
  email: false
