language: bash

services:
  - docker

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - build.sh install-terraform

env:
  - JOB="terraform"
  - JOB="docker"

script: build.sh "$JOB"
