language: bash

services:
  - docker

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

stages:
  - build
  - deploy

jobs:
  include:
    - stage: build
      script: $TRAVIS_BUILD_DIR/build.sh docker
    - stage: deploy
      script: $TRAVIS_BUILD_DIR/build.sh terraform

branches:
  only:
    - master

notifications:
  email: false
