"arch":
- "arm64"
"branches":
  "only":
  - "master"
"jobs":
  "include":
  - "script":
    - "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin"
    - "docker-compose -f $TRAVIS_BUILD_DIR/docker/docker-compose.yml build --parallel"
    - "docker-compose -f $TRAVIS_BUILD_DIR/docker/docker-compose.yml push"
    "stage": "docker"
"language": "bash"
"notifications":
  "email": false
"services":
- "docker"
