"branches":
  "only":
  - "master"
"jobs":
  "include":
  - "script": "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin"
    "stage": "docker login"
  - "script": "docker-compose -f $TRAVIS_BUILD_DIR/docker/docker-compose.yml build --parallel"
    "stage": "docker build"
"language": "bash"
"notifications":
  "email": false
"services":
- "docker"
