version: '3'

services:
  chorebot:
    image: arecker/chorebot:latest
    build:
      context: chorebot

  secretboi:
    image: arecker/secretboi:latest
    build:
      context: secretboi

  vault:
    image: arecker/vault:latest
    build:
      context: vault
