version: '3'

services:
  awscli:
    image: arecker/awscli:latest
    build:
      context: awscli

  jenkins:
    image: arecker/jenkins:latest
    build:
      context: jenkins

  slave:
    image: arecker/slave:latest
    build:
      context: slave

  proxy:
    image: arecker/proxy:latest
    build:
      context: proxy

  terraform:
    image: arecker/terraform:latest
    build:
      context: terraform
