---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: manifestor
  namespace: reckerbot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manifestor
  namespace: reckerbot
rules:
- apiGroups: [""]
  resources:
  - deployments
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manifestor
subjects:
- kind: ServiceAccount
  name: manifestor
roleRef:
  kind: Role
  name: manifestor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: manifestor
  namespace: reckerbot
spec:
  serviceAccountName: manifestor
  containers:
  - name: manifestor
    image: arecker/manifestor:latest
    imagePullPolicy: Always
    env:
    - name: MANIFEST_URL
      value: https://github.com/arecker/reckerbot/blob/master/kubernetes.yml
