"all":
  "hosts":
    "chores.local":
      "ansible_become_pass": "{{ secrets.sudo }}"
      "ansible_python_interpreter": "/usr/bin/python3"
      "user": "alex"
    "console.local":
      "ansible_become_pass": "{{ secrets.sudo }}"
      "ansible_python_interpreter": "/usr/bin/python3"
      "user": "alex"
    "jenkins.local":
      "ansible_become_pass": "{{ secrets.sudo }}"
      "ansible_python_interpreter": "/usr/bin/python3"
      "user": "alex"
    "minecraft.local":
      "ansible_become_pass": "{{ secrets.sudo }}"
      "ansible_python_interpreter": "/usr/bin/python3"
      "user": "alex"
    "printer.local":
      "ansible_become_pass": "{{ secrets.sudo }}"
      "ansible_python_interpreter": "/usr/bin/python3"
      "user": "alex"
    "wallpaper.local":
      "ansible_become_pass": "{{ secrets.sudo }}"
      "ansible_python_interpreter": "/usr/bin/python3"
      "user": "alex"
