apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: farm-ingress
spec:
  rules:
  - host: hub.local
    http:
      paths:
      - backend:
          serviceName: hub
          servicePort: 80
  - host: vault.local
    http:
      paths:
      - backend:
          serviceName: vault
          servicePort: 8200
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: chorebot
spec:
  schedule: "0 10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: secrets
              emptyDir: {}
          containers:
          - name: secrets
            image: arecker/secretboi:latest
            imagePullPolicy: Always
            env:
              - name: VAULT_ADDR
                value: "http://vault.local"
              - name: VAULT_ROLE
                value: chorebot
              - name: ONLY_RUN_ONCE
                value: "true"
              - name: SECRET_WEBHOOK
                value: /slack/reckerfamily/webhook
            volumeMounts:
              - name: secrets
                mountPath: /secrets
          - name: script
            image: arecker/chorebot:latest
            imagePullPolicy: Always
            volumeMounts:
              - name: secrets
                mountPath: /secrets
                readOnly: true
