apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: farm-ingress
spec:
  rules:
  - host: hub.local
    http:
      paths:
      - backend:
          serviceName: hub-proxy
          servicePort: 80
  - host: jenkins.local
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 80
