apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  restartPolicy: Never
  volumes:
  - name: shared
    emptyDir: {}
  containers:
  - name: secrets
    image: arecker/secretboi:latest
    volumeMounts:
    - name: secrets
      mountPath: /secretboi
  - name: 
    image: debian
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 5; echo \"Running...\"; done;" ]
    volumeMounts:
    - name: vault
      mountPath: /vault
