---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: vault-volume
  labels:
    app: vault
spec:
  storageClassName: generic
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: archive.local
    path: /mnt/scratch/farm/vault
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vault-volume-claim
  labels:
    app: vault
spec:
  storageClassName: generic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vault-app
  labels:
    app: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
        service: vault
    spec:
      containers:
        - name: vault-app
          image: arecker/vault:latest
          imagePullPolicy: Always
          command: ["vault", "server", "-config=/vault/config/vault.hcl"]
          securityContext:
            runAsUser: 1001
          ports:
            - containerPort: 8200
          volumeMounts:
            - mountPath: /vault/file
              name: vault-data
      volumes:
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  ports:
  - port: 8200
    protocol: TCP
  selector:
    service: vault

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
