---
- "handlers":
  - "name": "restart chores service"
    "systemd":
      "daemon_reload": true
      "name": "chores"
      "scope": "user"
      "state": "restarted"
  "hosts": "dev.local"
  "name": "chores"
  "remote_user": "alex"
  "tasks":
  - "copy":
      "dest": "~/bin/{{ item }}"
      "mode": "0755"
      "src": "bin/{{ item }}"
    "name": "bin: {{ item }}"
    "notify":
    - "restart chores service"
    "with_items":
    - "chorebot"
    - "chores"
  - "git":
      "dest": "~/src/chores"
      "repo": "https://www.github.com/arecker/chores.git"
      "version": "master"
    "name": "git: ~/src/chores"
    "notify":
    - "restart chores service"
  - "name": "venv: chores"
    "notify":
    - "restart chores service"
    "pip":
      "requirements": "~/src/chores/requirements.txt"
      "virtualenv": "~/venvs/chores"
      "virtualenv_command": "pyvenv"
  - "become": false
    "name": "template: ~/envs/chores.env"
    "notify":
    - "restart chores service"
    "template":
      "dest": "~/envs/chores.env"
      "mode": "0700"
      "src": "env.j2"
    "vars":
      "variables":
        "DB_PATH": "sqlite:////home/alex/mnt/chores.db"
        "FLASK_ENV": "production"
        "HUB_URL": "http://chores.local"
        "PYTHONDONTWRITEBYTECODE": "1"
        "PYTHONUNBUFFERED": "1"
        "WEBHOOK_URL": "{{ secrets.chores_webhook_url }}"
  - "cron":
      "hour": "10"
      "job": "$HOME/bin/chorebot &> /dev/null"
      "minute": "0"
      "name": "chorebot"
    "name": "cron: chorebot"
  - "become": false
    "name": "template: ~/.config/systemd/user/chores.service"
    "notify":
    - "restart chores service"
    "template":
      "dest": "~/.config/systemd/user/chores.service"
      "mode": "0700"
      "src": "service.j2"
    "vars":
      "variables":
        "command": "%h/bin/chores"
        "description": "chores service"
        "envFile": "%h/envs/chores.env"
  - "name": "sevice: chores"
    "systemd":
      "daemon_reload": true
      "enabled": true
      "name": "chores"
      "scope": "user"
      "state": "started"
  "vars_files": "secrets.yml"
...

