- "handlers":
  - "become": true
    "name": "restart nginx service"
    "systemd":
      "daemon_reload": true
      "enabled": true
      "name": "nginx"
      "scope": "system"
      "state": "reloaded"
  "hosts": "chores.local"
  "name": "chores"
  "tasks":
  - "become": true
    "name": "package: {{ item }}"
    "package":
      "name": "{{ item }}"
      "state": "present"
      "update_cache": false
    "with_items":
    - "git"
    - "nginx"
  - "become": false
    "file":
      "mode": "0751"
      "path": "{{ item }}"
      "state": "directory"
    "name": "directory: {{ item }}"
    "with_items":
    - "~/bin"
    - "~/src/"
    - "~/envs"
    - "~/venvs"
  - "copy":
      "dest": "~/bin/{{ item }}"
      "mode": "0755"
      "src": "bin/{{ item }}"
    "name": "bin: {{ item }}"
    "with_items":
    - "chorebot"
  - "become": false
    "git":
      "dest": "~/src/chores"
      "repo": "https://www.github.com/arecker/chores.git"
      "version": "master"
    "name": "git: ~/src/chores"
  - "become": false
    "name": "template: ~/envs/chores.env"
    "template":
      "dest": "~/envs/chores.env"
      "mode": "0700"
      "src": "env.j2"
    "vars":
      "variables":
        "DB_PATH": "sqlite:////home/alex/chores.db"
        "FLASK_ENV": "production"
        "HUB_URL": "http://chores.local"
        "PORT": 5000
        "PYTHONDONTWRITEBYTECODE": "1"
        "PYTHONUNBUFFERED": "1"
        "WEBHOOK_URL": "{{ secrets.chores_webhook_url }}"
  - "become": true
    "name": "template: /etc/nginx/nginx.conf"
    "notify":
    - "restart nginx service"
    "template":
      "dest": "/etc/nginx/nginx.conf"
      "mode": "0700"
      "src": "nginx/app.conf.j2"
    "vars":
      "variables":
        "port": 5000
  - "become": true
    "name": "sevice: nginx"
    "systemd":
      "daemon_reload": true
      "enabled": true
      "name": "nginx"
      "scope": "system"
      "state": "started"
  "vars_files": "secrets/secrets.yml"
