---
- "hosts": "dev.local"
  "name": "chores"
  "remote_user": "alex"
  "tasks":
  - "copy":
      "dest": "~/bin/{{ item }}"
      "mode": "0755"
      "src": "bin/{{ item }}"
    "name": "bin: {{ item }}"
    "with_items":
    - "chorebot"
    - "chores"
  - "git":
      "dest": "~/src/chores"
      "repo": "https://www.github.com/arecker/chores.git"
      "version": "master"
    "name": "git: ~/src/chores"
  - "name": "venv: chores"
    "pip":
      "requirements": "~/src/chores/requirements.txt"
      "virtualenv": "~/venvs/chores"
      "virtualenv_command": "pyvenv"
  - "name": "template: ~/envs/chores.env"
    "template":
      "dest": "~/envs/chores.env"
      "mode": "0700"
      "src": "env.j2"
    "vars":
      "variables":
        "DB_PATH": "sqlite:///$HOME/mnt/chores.db"
        "FLASK_ENV": "production"
        "HUB_URL": "http://chores.local"
        "PYTHONDONTWRITEBYTECODE": "1"
        "PYTHONUNBUFFERED": "1"
        "WEBHOOK_URL": "{{ secrets.chores_webhook_url }}"
  - "cron":
      "hour": "10"
      "job": "$HOME/bin/chorebot &> /dev/null"
      "minute": "0"
      "name": "chorebot"
    "name": "cron: chorebot"
  "vars_files": "secrets.yml"
...

