- "hosts": "jenkins.local"
  "tasks":
  - "become": true
    "copy":
      "dest": "/var/lib/jenkins/.ssh/id_rsa"
      "group": "jenkins"
      "mode": "0600"
      "owner": "jenkins"
      "src": "keys/jenkins.priv"
      "state": "present"
  - "become": true
    "package":
      "name": "{{ item }}"
      "state": "present"
    "with_items":
    - "curl"
    - "git"
    - "bash"
  "vars":
    "ansible_python_interpreter": "/usr/bin/python3"
    "ansible_user": "jenkins"
