---
- "handlers":
  - "become": true
    "name": "restart nginx service"
    "systemd":
      "daemon_reload": true
      "enabled": true
      "name": "nginx"
      "scope": "system"
      "state": "reloaded"
  "hosts": "dev.local"
  "name": "dev server"
  "tasks":
  - "become": true
    "name": "template: /etc/hosts"
    "template":
      "dest": "/etc/hosts"
      "mode": "0644"
      "src": "hosts.j2"
    "vars":
      "variables":
        "chores.local": 5000
        "wallpaper.local": 5001
  - "become": true
    "name": "template: /etc/apt/sources.list.d/ansible.list"
    "template":
      "dest": "/etc/apt/sources.list.d/ansible.list"
      "mode": "0744"
      "src": "ansible.list.j2"
    "vars":
      "variables": {}
  - "apt_key":
      "id": "93C4A3FD7BB9C367"
      "keyserver": "keyserver.ubuntu.com"
      "state": "present"
    "become": true
    "name": "apt-key: 93C4A3FD7BB9C367"
  - "become": true
    "name": "package: {{ item }}"
    "package":
      "name": "{{ item }}"
      "state": "present"
      "update_cache": false
    "with_items":
    - "git"
    - "nfs-common"
    - "nginx"
    - "python3"
    - "python3-pip"
    - "python3-setuptools"
    - "python3-venv"
  - "become": true
    "name": "package: ansible"
    "package":
      "name": "ansible"
      "state": "present"
      "update_cache": true
  - "file":
      "mode": "0751"
      "path": "{{ item }}"
      "state": "directory"
    "name": "directory: {{ item }}"
    "with_items":
    - "~/.config/systemd/user/"
    - "~/bin"
    - "~/envs"
    - "~/src"
    - "~/venvs"
  - "become": true
    "name": "template: /etc/nginx/nginx.conf"
    "notify":
    - "restart nginx service"
    "template":
      "dest": "/etc/nginx/nginx.conf"
      "mode": "0700"
      "src": "nginx.conf.j2"
    "vars":
      "variables":
        "chores.local": 5000
        "wallpaper.local": 5001
  - "become": true
    "name": "sevice: nginx"
    "systemd":
      "daemon_reload": true
      "enabled": true
      "name": "nginx"
      "scope": "system"
      "state": "started"
  "vars_files": "secrets/secrets.yml"
...

