---
- "hosts": "dev.local"
  "name": "dev server"
  "remote_user": "alex"
  "tasks":
  - "become": true
    "name": "package: {{ item }}"
    "package":
      "name": "{{ item }}"
      "state": "present"
    "with_items":
    - "git"
    - "python3"
    - "python3-pip"
    - "python3-setuptools"
    - "python3-venv"
  - "file":
      "mode": "0751"
      "path": "{{ item }}"
      "state": "directory"
    "name": "directory: {{ item }}"
    "with_items":
    - "~/envs"
    - "~/src"
    - "~/venvs"
  - "git":
      "dest": "~/src/chores"
      "repo": "https://www.github.com/arecker/chores.git"
      "version": "master"
    "name": "git: ~/src/chores"
  - "name": "venv: chores"
    "pip":
      "requirements": "~/src/chores/requirements.txt"
      "virtualenv": "~/venvs/chores"
      "virtualenv_command": "pyvenv"
  - "name": "template: ~/envs/chores.env"
    "template":
      "dest": "~/envs/chores.env"
      "mode": "0600"
      "src": "env.j2"
    "vars":
      "variables":
        "HUB_URL": "http://chores.local"
        "WEBHOOK_URL": "{{ secrets.chores_webhook_url }}"
  "vars_files": "secrets.yml"
...

