---
- "hosts": "dev.local"
  "name": "dev server"
  "remote_user": "alex"
  "tasks":
  - "become": true
    "name": "package: {{ item }}"
    "package":
      "name": "{{ item }}"
      "state": "present"
    "with_items":
    - "git"
    - "nfs-common"
    - "python3"
    - "python3-pip"
    - "python3-setuptools"
    - "python3-venv"
  - "file":
      "mode": "0751"
      "path": "{{ item }}"
      "state": "directory"
    "name": "directory: {{ item }}"
    "with_items":
    - "~/bin"
    - "~/envs"
    - "~/src"
    - "~/venvs"
  - "copy":
      "dest": "~/bin/{{ item }}"
      "mode": "0755"
      "src": "bin/{{ item }}"
    "name": "bin: {{ item }}"
    "with_items":
    - "chorebot"
  - "git":
      "dest": "~/src/chores"
      "repo": "https://www.github.com/arecker/chores.git"
      "version": "master"
    "name": "git: ~/src/chores"
  - "name": "venv: chores"
    "pip":
      "requirements": "~/src/chores/requirements.txt"
      "virtualenv": "~/venvs/chores"
      "virtualenv_command": "pyvenv"
  - "name": "template: ~/envs/chores.env"
    "template":
      "dest": "~/envs/chores.env"
      "mode": "0700"
      "src": "env.j2"
    "vars":
      "variables":
        "FLASK_ENV": "production"
        "HUB_URL": "http://chores.local"
        "PYTHONDONTWRITEBYTECODE": "1"
        "PYTHONUNBUFFERED": "1"
        "WEBHOOK_URL": "{{ secrets.chores_webhook_url }}"
  - "cron":
      "hour": "10"
      "job": "$HOME/bin/chorebot &> /dev/null"
      "minute": "0"
      "name": "chorebot"
    "name": "cron: chorebot"
  "vars_files": "secrets.yml"
...

