---
- "hosts": "dev.local"
  "name": "dev server"
  "remote_user": "alex"
  "tasks":
  - "become": true
    "name": "template: /etc/hosts"
    "template":
      "dest": "/etc/hosts"
      "mode": "0644"
      "src": "hosts.j2"
    "vars":
      "variables":
        "chores.local": 5000
  - "become": true
    "name": "package: {{ item }}"
    "package":
      "name": "{{ item }}"
      "state": "present"
    "with_items":
    - "git"
    - "nfs-common"
    - "nginx"
    - "python3"
    - "python3-pip"
    - "python3-setuptools"
    - "python3-venv"
  - "file":
      "mode": "0751"
      "path": "{{ item }}"
      "state": "directory"
    "name": "directory: {{ item }}"
    "with_items":
    - "~/.config/systemd/user/"
    - "~/bin"
    - "~/envs"
    - "~/mnt"
    - "~/src"
    - "~/venvs"
  - "become": true
    "mount":
      "fstype": "nfs"
      "path": "/home/alex/mnt"
      "src": "nas.local:/volume1/dev"
      "state": "present"
    "name": "mount: /home/alex/mnt"
  - "become": true
    "name": "template: /etc/nginx/nginx.conf"
    "template":
      "dest": "/etc/nginx/nginx.conf"
      "mode": "0700"
      "src": "nginx.conf.j2"
    "vars":
      "variables":
        "chores.local": 5000
...

