---
- "hosts": "jenkins.local"
  "name": "jenkins server"
  "tasks":
  - "become": true
    "name": "package: {{ item }}"
    "package":
      "name": "{{ item }}"
      "state": "present"
      "update_cache": false
    "with_items":
    - "default-jdk"
    - "git"
    - "gnupg2"
    - "python3"
    - "python3-pip"
    - "wget"
  - "apt_key":
      "state": "present"
      "url": "https://pkg.jenkins.io/debian/jenkins.io.key"
    "become": true
    "name": "apt-key: https://pkg.jenkins.io/debian/jenkins.io.key"
  - "become": true
    "name": "template: /etc/apt/sources.list.d/jenkins.list"
    "template":
      "dest": "/etc/apt/sources.list.d/jenkins.list"
      "mode": "0744"
      "src": "jenkins.list.j2"
    "vars":
      "variables": {}
  - "become": true
    "name": "template: /etc/default/jenkins"
    "template":
      "dest": "/etc/default/jenkins"
      "mode": "0644"
      "src": "jenkins.env.j2"
    "vars":
      "variables": {}
  - "become": true
    "name": "package: jenkins"
    "package":
      "name": "jenkins"
      "state": "present"
      "update_cache": true
  - "become": true
    "name": "sevice: jenkins"
    "systemd":
      "daemon_reload": true
      "enabled": true
      "name": "jenkins"
      "scope": "system"
      "state": "started"
  "vars_files": "secrets/secrets.yml"
...

