---
- "handlers":
  - "become": true
    "name": "restart nginx service"
    "systemd":
      "daemon_reload": true
      "enabled": true
      "name": "nginx"
      "scope": "system"
      "state": "reloaded"
  "hosts": "jenkins.local"
  "name": "jenkins server"
  "tasks":
  - "become": true
    "name": "package: {{ item }}"
    "package":
      "name": "{{ item }}"
      "state": "present"
      "update_cache": false
    "with_items":
    - "bats"
    - "curl"
    - "default-jdk"
    - "dnsutils"
    - "git"
    - "gnupg2"
    - "nginx"
    - "python3"
    - "python3-pip"
    - "wget"
  - "apt_key":
      "state": "present"
      "url": "https://pkg.jenkins.io/debian/jenkins.io.key"
    "become": true
    "name": "apt-key: https://pkg.jenkins.io/debian/jenkins.io.key"
  - "become": true
    "name": "template: /etc/apt/sources.list.d/jenkins.list"
    "template":
      "dest": "/etc/apt/sources.list.d/jenkins.list"
      "mode": "0744"
      "src": "jenkins.list.j2"
    "vars":
      "variables": {}
  - "become": true
    "name": "template: /etc/default/jenkins"
    "template":
      "dest": "/etc/default/jenkins"
      "mode": "0644"
      "src": "jenkins.env.j2"
    "vars":
      "variables": {}
  - "become": true
    "name": "package: jenkins"
    "package":
      "name": "jenkins"
      "state": "present"
      "update_cache": true
  - "become": true
    "name": "sevice: jenkins"
    "systemd":
      "daemon_reload": true
      "enabled": true
      "name": "jenkins"
      "scope": "system"
      "state": "started"
  - "become": false
    "file":
      "group": "jenkins"
      "mode": "700"
      "owner": "jenkins"
      "path": "/var/lib/jenkins/.ssh"
      "state": "directory"
    "name": "directory: /var/lib/jenkins/.ssh"
  - "become": true
    "name": "template: /var/lib/jenkins/.ssh/id_rsa"
    "template":
      "dest": "/var/lib/jenkins/.ssh/id_rsa"
      "group": "jenkins"
      "mode": "700"
      "owner": "jenkins"
      "src": "file.j2"
    "vars":
      "variables":
        "content": "{{ secrets.jenkins.private }}"
  - "become": true
    "name": "template: /etc/nginx/nginx.conf"
    "notify":
    - "restart nginx service"
    "template":
      "dest": "/etc/nginx/nginx.conf"
      "mode": "0700"
      "src": "nginx/jenkins.conf.j2"
    "vars":
      "variables": {}
  - "become": true
    "name": "sevice: nginx"
    "systemd":
      "daemon_reload": true
      "enabled": true
      "name": "nginx"
      "scope": "system"
      "state": "started"
  - "become": true
    "name": "pip: ansible"
    "pip":
      "name": "ansible"
  - "become": true
    "name": "untar jsonnet"
    "unarchive":
      "dest": "/usr/local/bin"
      "remote_src": true
      "src": "https://github.com/google/jsonnet/releases/download/v0.17.0/jsonnet-bin-v0.17.0-linux.tar.gz"
  - "become": true
    "file":
      "dest": "/usr/bin/python"
      "src": "/usr/bin/python3"
      "state": "link"
    "name": "fix python with symlink"
  "vars_files": "secrets/secrets.yml"
...

