---
- "hosts": "dev.local"
  "name": "minecraft server"
  "tasks":
  - "file":
      "mode": "0751"
      "path": "~/minecraft"
      "state": "directory"
    "name": "directory: ~/minecraft"
  - "get_url":
      "dest": "~/minecraft/server.jar"
      "url": "https://launcher.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar"
    "name": "get_url: ~/minecraft/server.jar"
  "vars_files": "secrets/secrets.yml"
...

