---
- "hosts": "dev.local"
  "name": "minecraft server"
  "tasks":
  - "become": true
    "name": "package: screen"
    "package":
      "name": "screen"
      "state": "present"
      "update_cache": false
  "vars_files": "secrets/secrets.yml"
...

