---
- "hosts": "dev.local"
  "name": "minecraft server"
  "tasks":
  - "become": true
    "name": "package: screen"
    "package":
      "name": "screen"
      "state": "present"
      "update_cache": false
  - "file":
      "mode": "0751"
      "path": "~/minecraft"
      "state": "directory"
    "name": "directory: ~/minecraft"
  - "get_url":
      "dest": "~/minecraft/server.jar"
      "url": "https://launcher.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar"
    "name": "get_url: ~/minecraft/server.jar"
  - "copy":
      "dest": "~/bin/{{ item }}"
      "mode": "0755"
      "src": "bin/{{ item }}"
    "name": "bin: {{ item }}"
    "with_items":
    - "minecraft"
    - "minecraft-backup"
  - "cron":
      "job": "~/bin/minecraft"
      "name": "minecraft server"
      "special_time": "reboot"
    "name": "cron: minecraft server"
  - "cron":
      "job": "~/bin/minecraft-backup"
      "name": "minecraft server backup"
      "special_time": "hourly"
    "name": "cron: minecraft server backup"
  "vars_files": "secrets/secrets.yml"
...

