---
- "handlers": []
  "hosts": "prod"
  "name": "php"
  "tasks":
  - "become": true
    "name": "package: {{ item }}"
    "package":
      "name": "{{ item }}"
      "state": "present"
      "update_cache": false
    "with_items":
    - "imagemagick"
    - "libapache2-mod-php"
    - "php"
    - "php-curl"
    - "php-mbstring"
    - "php-mysql"
    - "php-xml"
  - "become": true
    "name": "template: /etc/php/7.3/apache2/php.ini"
    "template":
      "dest": "/etc/php/7.3/apache2/php.ini"
      "mode": "0644"
      "src": "php.ini.j2"
    "vars":
      "variables": {}
  "vars_files": "secrets/secrets.yml"
...

