- "handlers":
  - "become": true
    "name": "restart ssh service"
    "systemd":
      "daemon_reload": true
      "enabled": true
      "name": "ssh"
      "scope": "system"
      "state": "restarted"
  "hosts":
  - "console.local"
  - "diningroom.local"
  - "minecraft.local"
  - "printer.local"
  - "chores.local"
  - "wallpaper.local"
  "name": "SSH keys"
  "tasks":
  - "become": true
    "name": "template: /etc/ssh/sshd_config"
    "notify":
    - "restart ssh service"
    "template":
      "dest": "/etc/ssh/sshd_config"
      "group": "root"
      "mode": "644"
      "owner": "root"
      "src": "sshd_config.j2"
    "vars":
      "variables": {}
  - "become": false
    "name": "template: ~/.ssh/authorized_keys"
    "template":
      "dest": "~/.ssh/authorized_keys"
      "mode": "0700"
      "src": "authorized_keys.j2"
    "vars":
      "variables":
        "public_keys":
        - "{{ secrets.public }}"
        - "{{ secrets.jenkins.public }}"
  "vars_files": "secrets/secrets.yml"
