---
- "handlers":
  - "become": false
    "name": "restart wallpaper service"
    "systemd":
      "daemon_reload": true
      "enabled": true
      "name": "wallpaper"
      "scope": "user"
      "state": "restarted"
  "hosts": "dev.local"
  "name": "wallpaper"
  "tasks":
  - "copy":
      "dest": "~/bin/{{ item }}"
      "mode": "0755"
      "src": "bin/{{ item }}"
    "name": "bin: {{ item }}"
    "notify":
    - "restart wallpaper service"
    "with_items":
    - "sync"
    - "wallpaper"
  - "git":
      "dest": "~/src/wallpaper"
      "repo": "https://www.github.com/arecker/wallpaper.git"
      "version": "master"
    "name": "git: ~/src/wallpaper"
  - "name": "venv: wallpaper"
    "pip":
      "requirements": "~/src/wallpaper/requirements.txt"
      "virtualenv": "~/venvs/wallpaper"
      "virtualenv_command": "pyvenv"
  - "copy":
      "dest": "~/.wallpaper.json"
      "mode": "640"
      "src": "secrets/credentials.json"
    "name": "copy: ~/.wallpaper.json"
  - "become": false
    "name": "template: ~/envs/wallpaper.env"
    "notify":
    - "restart wallpaper service"
    "template":
      "dest": "~/envs/wallpaper.env"
      "mode": "0700"
      "src": "env.j2"
    "vars":
      "variables":
        "FLASK_APP": "app.py"
        "FLASK_ENV": "production"
        "GPHOTOS_COMMAND_PATH": "$HOME/venvs/wallpaper/bin/gphotos-sync"
        "PORT": 5001
        "SECRET_PATH": "$HOME/.wallpaper.json"
        "STORAGE_PATH": "$HOME/mnt/wallpaper"
  - "become": false
    "name": "template: ~/.config/systemd/user/wallpaper.service"
    "notify":
    - "restart wallpaper service"
    "template":
      "dest": "~/.config/systemd/user/wallpaper.service"
      "mode": "0700"
      "src": "service.j2"
    "vars":
      "variables":
        "command": "%h/bin/wallpaper"
        "description": "wallpaper service"
        "envFile": "%h/envs/wallpaper.env"
  - "become": false
    "name": "sevice: wallpaper"
    "systemd":
      "daemon_reload": true
      "enabled": true
      "name": "wallpaper"
      "scope": "user"
      "state": "started"
  "vars_files": "secrets/secrets.yml"
...

