---
- "handlers":
  - "become": false
    "name": "restart wallpaper service"
    "systemd":
      "daemon_reload": true
      "enabled": true
      "name": "wallpaper"
      "scope": "user"
      "state": "restarted"
  - "become": true
    "name": "restart nginx service"
    "systemd":
      "daemon_reload": true
      "enabled": true
      "name": "nginx"
      "scope": "system"
      "state": "reloaded"
  "hosts": "wallpaper.local"
  "name": "wallpaper"
  "tasks":
  - "become": true
    "name": "package: {{ item }}"
    "package":
      "name": "{{ item }}"
      "state": "present"
      "update_cache": false
    "with_items":
    - "git"
    - "nginx"
    - "python3"
    - "python3-pip"
    - "python3-setuptools"
    - "python3-venv"
  - "become": false
    "file":
      "mode": "0751"
      "path": "{{ item }}"
      "state": "directory"
    "name": "directory: {{ item }}"
    "with_items":
    - "~/bin"
    - "~/wallpaper"
    - "~/src/"
    - "~/envs"
    - "~/venvs"
    - "~/.config/systemd/user"
  - "copy":
      "dest": "~/bin/{{ item }}"
      "mode": "0755"
      "src": "bin/{{ item }}"
    "name": "bin: {{ item }}"
    "notify":
    - "restart wallpaper service"
    "with_items":
    - "sync"
    - "wallpaper"
  - "git":
      "dest": "~/src/wallpaper"
      "repo": "https://www.github.com/arecker/wallpaper.git"
      "version": "master"
    "name": "git: ~/src/wallpaper"
    "notify":
    - "restart wallpaper service"
  - "become": false
    "name": "template: $HOME/.wallpaper.json"
    "template":
      "dest": "$HOME/.wallpaper.json"
      "mode": "0700"
      "src": "file.j2"
    "vars":
      "variables":
        "content": "{{ secrets.wallpaper }}"
  - "name": "venv: wallpaper"
    "notify":
    - "restart wallpaper service"
    "pip":
      "requirements": "~/src/wallpaper/requirements.txt"
      "virtualenv": "~/venvs/wallpaper"
      "virtualenv_command": "pyvenv"
  - "become": false
    "name": "template: ~/envs/wallpaper.env"
    "notify":
    - "restart wallpaper service"
    "template":
      "dest": "~/envs/wallpaper.env"
      "mode": "0700"
      "src": "env.j2"
    "vars":
      "variables":
        "FLASK_APP": "app.py"
        "FLASK_ENV": "production"
        "GPHOTOS_COMMAND_PATH": "$HOME/venvs/wallpaper/bin/gphotos-sync"
        "PORT": 5001
        "SECRET_PATH": "$HOME/.wallpaper.json"
        "STORAGE_PATH": "$HOME/wallpaper"
  - "become": false
    "name": "template: ~/.config/systemd/user/wallpaper.service"
    "notify":
    - "restart wallpaper service"
    "template":
      "dest": "~/.config/systemd/user/wallpaper.service"
      "mode": "0700"
      "src": "service.j2"
    "vars":
      "variables":
        "command": "%h/bin/wallpaper"
        "description": "wallpaper service"
        "envFile": "%h/envs/wallpaper.env"
  - "become": false
    "name": "sevice: wallpaper"
    "systemd":
      "daemon_reload": true
      "enabled": true
      "name": "wallpaper"
      "scope": "user"
      "state": "started"
  - "become": true
    "name": "template: /etc/nginx/nginx.conf"
    "notify":
    - "restart nginx service"
    "template":
      "dest": "/etc/nginx/nginx.conf"
      "mode": "0700"
      "src": "nginx/app.conf.j2"
    "vars":
      "variables":
        "port": 5001
  - "become": true
    "name": "sevice: nginx"
    "systemd":
      "daemon_reload": true
      "enabled": true
      "name": "nginx"
      "scope": "system"
      "state": "started"
  "vars_files": "secrets/secrets.yml"
...

